### ISSUE TITLE
loadTranslations doesn't work in main.ts

### ISSUE THREAD

**Issue by adwiens** [loclapp/locl#8] opened 2020-02-06 20:54 UTC
I may be missing something, but since at least rc12 I haven't been able to use loadTranslations in main.ts. There are no error messages, but the original (untranslated) string remains unchanged.

[Example repo](https://github.com/adwiens-spikes/ng9-locl-i18n)

The readme says 9rc12, but it's been upgraded to 9.0.0 and the same behavior occurs.

The loadTranslations call works if called _synchronously_ in polyfills.ts, but it does not work if called in a resolved Promise (eg. a fetch) in polyfills.ts or in main.ts.

This is pretty important since the behavior of loadTranslations seems to imply that doing an ajax request for the JSON can't work, since the JSON necessarily won't be available synchronously in polyfills.ts.

Hopefully I'm just missing something?

As a simple workaround, I can require() the JSON files in polyfills.ts, but then all locales become part of the bundle.

**Comment by ocombe** [comment] 2020-02-06 21:21
Hello !

It works if you change main.ts to:

```
import '@angular/localize/init';

import { loadTranslations } from '@angular/localize';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { getTranslations, ParsedTranslationBundle } from '@locl/core';


getTranslations('/assets/i18n/fr.json').then(
  (data: ParsedTranslationBundle) => {
    console.warn(data);
    loadTranslations(data as any);
    import('./app/app.module').then(module => {
      platformBrowserDynamic()
        .bootstrapModule(module.AppModule)
        .catch(err => console.error(err));
    });
  }
);
```

The problem is that `$localize` calls are defined as constants outside of the template creation, so whenever there is a call to import the module, the javascript code for that module is executed, and the translations are defined before the translation file is loaded.

By moving the import of the module to a dynamic `import()`, webpack will wrap the module code in a closure that is only executed after loading the translations.

I've reported this problem to the Angular team, it's planned to move the `$localize` code to its own closure that is only executed when the templates are created, but unfortunately that's not the case for now.

Sometimes it still works, depending how webpack loads the files. I'm not quite sure why it stopped working in your case, maybe because of your version of angular CLI and its webpack dependency...

In any case I should add this explanation and example to the docs, until that problem is fixed in `@angular/core`. Thanks.

**Comment by ocombe** [comment] 2020-02-06 21:42
Ok I managed to find what was causing my demo app to work, and your app to fail: in angular.json you have the config defined with `"aot": true`, while my demo app has `"aot": false`.
I tried to build my demo with aot set to `true` and it fails in the same way (in dev, and in prod build).

So it looks like I need to update my documentation right now, thanks!

**Closed** 2020-02-06 22:00 UTC
Labels: documentation
